server:
  port: 4004

spring:
  sql:
      init:
        mode: always
        schema-locations: classpath:schema-h2.sql
        continue-on-error: true
  datasource:
    url: jdbc:h2:mem:space;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

cds:
  security:
    mock:
      enabled: true
      users:
        admin:    { password: admin,    roles: [SpacefarerAdmin],      attributes: { originPlanet: "Terra Nova" } }
        lynda:    { password: lynda,    roles: [SpacefarerLieutenant], attributes: { originPlanet: "Kepler-62f" } }
        cadetx:   { password: cadetx,   roles: [SpacefarerCadet],      attributes: { originPlanet: "Umbra Nine" } }
        cadetlyr: { password: cadetlyr, roles: [SpacefarerCadet],      attributes: { originPlanet: "Lyra Station" } }
spacefarer:
  notifications:
    # Configure the sender address used for outgoing welcome emails. Falls back to spring.mail.username when empty.
    from: "noreply@galactic-spacefarer.com"