server:
  port: 4004

spring:
  sql:
      init:
        mode: always
        schema-locations: classpath:schema-h2.sql
        continue-on-error: true
  datasource:
    url: jdbc:h2:mem:space;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

cds:
  security:
    mock:
      enabled: true
      users:
        admin: { password: admin, roles: [SpaceAdmin], attributes: { planet: "HQ" } }
        alice: { password: alice, roles: [SpaceUser], attributes: { planet: "X" } }
        bob:   { password: bob,   roles: [SpaceUser], attributes: { planet: "Y" } }