server:
  port: 4004

spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-sqlite.sql
      continue-on-error: true
  datasource:
    url: jdbc:sqlite:file:./data/spacefarer.db
    driverClassName: org.sqlite.JDBC
    username:
    password:

cds:
  security:
    mock:
      enabled: true
      users:
        admin:    { password: admin,    roles: [SpacefarerAdmin],      attributes: { originPlanet: "Terra Nova" } }
        lynda:    { password: lynda,    roles: [SpacefarerLieutenant], attributes: { originPlanet: "Kepler-62f" } }
        cadetx:   { password: cadetx,   roles: [SpacefarerCadet],      attributes: { originPlanet: "Umbra Nine" } }
        cadetlyr: { password: cadetlyr, roles: [SpacefarerCadet],      attributes: { originPlanet: "Lyra Station" } }
spacefarer:
  notifications:
    # Configure the sender address used for outgoing welcome emails. Falls back to spring.mail.username when empty.
    from: "noreply@galactic-spacefarer.com"